name: Deploy Frontend ke Google App Engine

on:
  push:
    branches:
      - frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tarik Kode dari Repository
        uses: actions/checkout@v4

      - name: Siapkan Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Suntikkan Semua Variabel Firebase & API ke .env
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_DATABASE_URL=${{ secrets.VITE_FIREBASE_DATABASE_URL }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
        working-directory: ./frontend

      - name: Build Aplikasi React (Vite)
        run: npm run build
        working-directory: ./frontend

      # --- BAGIAN KHUSUS GOOGLE CLOUD ---
      - name: Autentikasi ke Google Cloud Platform
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy ke Google App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          working_directory: ./frontend
          deliverables: app.yaml